[package]
name = "sigmorph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
char_reader = "0.1.1"
clap = {version = "4.3.24", features = ["derive"]}
rstest = "0.18.2"
